const customersData = [
  {id: 0, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 1, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 2, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 3, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 4, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 5, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 6, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 7, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 8, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 9, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 10, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 11, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 12, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 13, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 14, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 15, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 16, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 17, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 18, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 19, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 20, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 21, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 22, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 23, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 24, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 25, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
  {id: 26, icon_src: 'avatars/1.jpg', name: 'John Doe', type: 'New', country:'USA', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
]

export default customersData
